### ISSUE TITLE
Atualizar dados de instalação no README

### ISSUE THREAD

**Issue by pgcalixto** [guaycuru/gde#16]
- [ ] Passo 3, o correto seria o termo **mover** o arquivo ao invés de **copiar**?
- [x] Detalhar mais o passo 4 sobre as possíveis modificações
- [x] Consertar o nome do pacote SQL: `gde42_pacote.sql` e colocar o nome em sintaxe de código (entre backticks: \`gde42_pacote.sql\`)
- [x] Adicionar informação no passo 6 de que é normal a importação do banco demorar, pois ele é bem grande (pra pessoa não dar Ctrl-C antes do tempo achando que deu erro em importar)

**Comment by guaycuru** [comment]
Olá, obrigado pelas sugestões. Quando ao passo 3, o correto é copiar mesmo, senão o arquivo de sample vai ficar faltando e o git vai reclamar. Vou corrigir o resto.
