### ISSUE TITLE
Crawl dos dados

### ISSUE THREAD

**Issue by ignacioespinoso** [guaycuru/gde#21]
Olá! Gostaria de saber como você faz o crawl dos dados da DAC, olhando o código e os commits não encontrei nada. Estou tentando fazer algo parecido, mas com foco maior na avialiação dos professores com base nos matriculados das turmas.

**Comment by guaycuru** [comment]
Olá,

Infelizmente a parte de crawl dos dados terá que permanecer fechada por
solicitação da DAC.

Em Sex, 15 de dez de 2017 22:43, Ignácio Espinoso Ribeiro <
notifications@github.com> escreveu:
