### ISSUE TITLE
Planejamento não mostra matérias a serem adicionadas

### ISSUE THREAD

**Issue by VictorJulianiR** [guaycuru/gde#33]
![image](https://user-images.githubusercontent.com/40750238/42144825-a409fd7c-7d93-11e8-8a50-61875c4fe559.png)

E agora? Socorro!

**Comment by guaycuru** [comment]
Essa pergunta já foi respondida nas perguntas frequentes: https://github.com/guaycuru/gde/wiki/FAQ

O GDE não sabe em quais disciplinas você foi aprovado(a).
Para corrigir isso, acesse o menu "Acadêmico -> Eliminar Disciplinas", ou localize as disciplinas nas quais você foi aprovado(a) e, na aba curso, marque a opção apropriada.
Caso esteja faltando alguma disciplina na lista do "Eliminar Disciplinas", realize uma busca no GDE pela disciplina em questão e, na aba "curso", marque a opção apropriada.

**Comment by VictorJulianiR** [comment]
Na verdade eu ja eliminei várias disciplinas ( inclusive de períodos mais adiantados), tanto que minha árvore com várias disciplinas a menos e mesmo assim ele não sugere nenhuma disciplina pra inclusão :(
