### ISSUE TITLE
Adicionar matriculas no Google Calendar automaticamente

### ISSUE THREAD

**Issue by carlosamds** [guaycuru/gde#37]
Criar automaticamente um calendário do Google com os horários de aulas.
Adicionar também datas como dias de atividade suspensa na UNICAMP e períodos de matrículas.

**Comment by carlosamds** [comment]
Estou já estou desenvolvendo uma solução :)

**Comment by guaycuru** [comment]
Opa, que legal @carlosamds , estou ansioso para ver seu pull request! :)

**Comment by jovit** [comment]
Isso seria muito útil, alguma novidade?

**Comment by guaycuru** [comment]
Resolvido em https://github.com/guaycuru/gde/commit/30dd8f7dd8e3fa86fd9ab50d03771e4ab0d417cc
