### ISSUE TITLE
Certificado de segurança expirado

### ISSUE THREAD

**Issue by lcnzg** [guaycuru/gde#40]
Não sei se já está sabendo, mas o certificado de segurança de grade.daconline.unicamp.br expirou.

`grade.daconline.unicamp.br uses an invalid security certificate. The certificate expired on November 22, 2018, 11:26:02 AM GMT-2. The current time is November 23, 2018, 7:44 AM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE`

**Comment by guaycuru** [comment]
Olá @lcnzg , ontem mesmo já solicitei ao centro de computação que renove o certificado e estou aguardando. Obrigado por avisar!
