### ISSUE TITLE
Adicionar período de matrícula no Planejador

### ISSUE THREAD

**Issue by Leandroafm21** [guaycuru/gde#42]
Embora seja uma informação de fácil acesso no site da DAC e amplamente divulgada em redes sociais, devido a estarem de férias muitos alunos acabam a perdendo.

Seria interessante se o período de matrícula (e, possivelmente, de alteração) fosse exibido no Planejador. Como a grande maioria dos alunos passa por lá, eles ficariam cientes o quanto antes.

**Comment by guaycuru** [comment]
Oi @Leandroafm21 , ótima ideia, vou tentar fazer essa alteração em breve!
Obrigado!
