### ISSUE TITLE
Alterar catálogo

### ISSUE THREAD

**Issue by DiegoAntonioli** [guaycuru/gde#49]
Seria possível mudar o catálogo do curso, pois alterei na DAC e não consigo usar o planejador para o catálogo atualizado.

**Comment by guaycuru** [comment]
Para alterar seu curso / catálogo / modalidade no GDE acesse o menu Social -> Editar Perfil, e altere-o na aba "Acadêmico".

**Comment by DiegoAntonioli** [comment]
Obrigado pela atenção.
At.te
Diego Antonioli Garcia
Em 05/08/2019 14:12, "Felipe Guaycuru de C. B. Franco" <
notifications@github.com> escreveu:
