### ISSUE TITLE
Pacote de dados

### ISSUE THREAD

**Issue by guaycuru** [guaycuru/gde#5]
Disponibilizar algum pacote de dados aleatórios ou do próprio usuário para quem não tem acesso ao banco de dados oficial do GDE.

**Comment by rmobis** [comment]
Tem algum jeito que a gente possa ajudar nisso? Acho que esse é o primeiro passo pro pessoal poder começar a realmente contribuir com código.

**Comment by guaycuru** [comment]
Hmm vou focar nisso, tentar liberar o mais cedo possível um pacote mínimo!

**Comment by guaycuru** [comment]
Disponibilizei o pacote em: https://gde.guaycuru.net/gde_pacote.zip . Para mais informações, leia o README
