### ISSUE TITLE
Frase

### ISSUE THREAD

**Issue by ignacioespinoso** [guaycuru/gde#50]
Olá! Minha namorada viu essa frase ![Frase](https://user-images.githubusercontent.com/13559848/69200844-2de18b80-0b1b-11ea-8446-00c6869d16f8.jpeg) e levantou que foi algo deu um certo incômodo (até porque tem nada a ver com o resto do conteúdo). Teria como retirar?

**Comment by guaycuru** [comment]
Olá. Essa frase é retirada de feeds da internet sobre o qual não temos controle sobre frases específicas. Como esse é o primeiro (e provavelmente) único problema com essa fonte, não vejo motivo para desativá-la. De qualquer forma peço desculpas pelo incômodo causado.
