### ISSUE TITLE
Não sei como reativar minha conta 

### ISSUE THREAD

**Issue by 232195** [guaycuru/gde#51]
Eu tinha desativado a minha conta. Mas não sei como reativar, não a nenhuma opção.
Preciso usar o gde com urgência rsrs

**Comment by guaycuru** [comment]
Olá, para reativar sua conta basta realizar login no GDE por meio da DAC.

**Comment by 232195** [comment]
Acabei de fazer isso, e ao fazer meu login pelo site da dac  sou redirecionada para o site do gde que pede novamente o login e senha.
E aí inserir continua a aparecer usuário inativo
