### ISSUE TITLE
Erro na funcionalidade de Integração com Google Calendar

### ISSUE THREAD

**Issue by lcnzg** [guaycuru/gde#53]
Ao selecionar a funcionalidade `Adicionar ao Google Calendar` para a grade **2020 - 1º Semestre**, recebo o erro: `O Período escolhido não está disponível para ser adicionado ao Calendar`

**Comment by guaycuru** [comment]
Olá,

Acredito que o problema tenha sido resolvido.
Por favor, verifique e me avise.

Obrigado

**Comment by lcnzg** [comment]
Olá, obrigado. O erro acima foi resolvido, mas agora após escolher a agenda e selecionar `Adicionar horários no calendário`, aparece uma tela escrito `Processando...` e não dá mais respostas. (Não adiciona os eventos no calendário).

**Comment by julio-barros-playkids** [comment]
A resposta dessa tela de Processando... é `no token!` proveniente do commit que adiciona o token csrfp

**Comment by guaycuru** [comment]
Olá,

Estamos em contato com a equipe do Google para autorizar nosso uso do Google Calendar.
Enquanto esse processo (burocrático) não for resolvido, infelizmente o problema persistirá.

**Comment by guaycuru** [comment]
Infelizmente não será possível resolver esse problema, e a integração com o Google Calendar será removida.

**Comment by guaycuru** [comment]
Integração desativada em https://github.com/guaycuru/gde/commit/51ecfcebc45481e1f31cd96d8dbb49d59f433280
