### ISSUE TITLE
Utilizar o esqueleto da árvore de matérias

### ISSUE THREAD

**Issue by FelipeSSaraiva** [guaycuru/gde#55]
Fala pessoal, fui EE014 e agora na vida profissional me pediram para desenvolver um catálogo de treinamentos. Lembrei que a árvore de matérias do GDE era bastante interativa, então gostaria de saber se poderia usar o esqueleto dela no meu projeto. Se sim, poderiam me ajudar como? Conheço pouco do GitHub, rs. Se puderem me contatar através do meu email pessoal <fdssaraiva@gmail.com> fico grato. Obrigado!

**Comment by guaycuru** [comment]
Olá,

Infelizmente estou muito sem tempo, mal tenho conseguido implementar as mudanças planejadas no GDE, não tenho como te ajudar com isso. Mas fique a vontade para usar o código do GDE como quiser.
