### ISSUE TITLE
Uma matéria não está sendo contabilizada

### ISSUE THREAD

**Issue by ThiagoCarrenho** [guaycuru/gde#59]
Fiz a matéria MS329 no 1s2020, aprovado, mas sem nota, no esquema S/I (Suficiente/Insuficiente) criado durante o período da pandemia. Esta matéria está presente na integralização da DAC, mas não está presente na integralização do GDE.

**Comment by guaycuru** [comment]
O GDE não tem como saber em quais disciplinas você foi aprovado(a).
Para corrigir isso, acesse o menu "Acadêmico -> Eliminar Disciplinas", ou localize as disciplinas nas quais você foi aprovado(a) e, na aba curso, marque a opção apropriada.
Caso esteja faltando alguma disciplina na lista do "Eliminar Disciplinas", realize uma busca no GDE pela disciplina em questão e, na aba "curso", marque a opção apropriada.
