### ISSUE TITLE
Disciplinas com status de "Aprovado - Suficiente" aparecem como Desistências na tabela de Matrículas

### ISSUE THREAD

**Issue by Leandroafm21** [guaycuru/gde#62]
Outro problema envolvendo as disciplinas com status de "Aprovado - Suficiente" (código 20): elas aparecem como Desistências na tabela de Matrículas.

Tentei dar uma olhada no [código](https://github.com/guaycuru/gde/blob/d518f4826ea85dcdeea76c694bbb4ea4594cff6c/classes/GDE/Aluno.php#L543) pra ver se conseguia corrigir mas <ins>parece</ins> que essa informação [vem](https://github.com/guaycuru/gde/blob/d518f4826ea85dcdeea76c694bbb4ea4594cff6c/classes/GDE/Aluno.php#L552) da parte "proibida" do código (não sei, manjo 0 de PHP, rsrs). Talvez o _crawler_ esteja reconhecendo como desistentes os alunos com esses códigos nas disciplinas, uma situação que deve ser mais comum nesse semestre (pelo menos um dos meus professores disse que vai utilizar esses conceitos dada a dificuldade de avaliação precisa no EAD, isso pode ter virado uma tendência!).

Imagem do problema com o meu usuário (171836) - também ocorre com MC050 no 2s2018:
![image](https://user-images.githubusercontent.com/24303149/116221272-d722ad00-a723-11eb-82dc-fc0d361b6950.png)

**Comment by guaycuru** [comment]
Olá, primeiramente obrigado por abrir uma issue com uma descrição tão clara!
Infelizmente sua teoria está incorreta. Na realidade o GDE usa uma abordagem muito simplista para determinar desistências: Se em algum momento determinado aluno está na lista de matriculados de um oferecimento, e num momento seguinte não está mais, o GDE assume uma desistência. Mas isso tem vários problemas, como inconsistências nas informações vindas da DAC, etc.
De qualquer forma isso não será mais um problema no futuro devido a algumas mudanças que estão ocorrendo na forma como o GDE recebe os dados da DAC.
Para o seu caso específico posso corrigir os dados manualmente, basta me informar quais oferecimentos estão connstando incorretamente como desistências na sua integralização, bem como o seu RA.

**Comment by guaycuru** [comment]
Olá,

Revendo esta issue notei que todos os dados já estavam disponíveis. Atualizei manualmente MC019, caso mais alguma esteja com esse problema, por favor reabra esta issue @Leandroafm21
