### ISSUE TITLE
O site não atualizou minha matrícula no último semestre.

### ISSUE THREAD

**Issue by ThcerblaMOkA** [guaycuru/gde#63]
Já havia começado um curso na Unicamp e saído sem me formar. Agora entrei de novo, mas o site do GDE não reconhece que voltei. Já atualizei meu curso e catálogo , mas continua dizendo "Egressado". Desse modo ele não mostra minhas matrículas em matérias no último semestre e eu não consigo eliminar matérias nem montar meu planejamento.

**Comment by guaycuru** [comment]
Na realidade isso é um problema causado pela alteração na forma como o GDE obtém os dados da DAC, que ocorreu no início do ano. Estou trabalhando para resolver isso. Ver #65
