### ISSUE TITLE
Matéria pré-requisito errada.

### ISSUE THREAD

**Issue by ThcerblaMOkA** [guaycuru/gde#64]
As matérias MC602 e MC404 estão com a lógica de pré-req invertida.
Está aparecendo que MC404 é um pré-requisito para MC602, sendo que é o contrário, já que MC602 deve ser cursada antes, e inclusive tem reserva para semestre anterior à MC404.

**Comment by guaycuru** [comment]
O problema foi corrigido, obrigado por avisar!
