### ISSUE TITLE
Menu de pesquisa inacessível por causa da faixa do github 

### ISSUE THREAD

**Issue by lucasvreis** [guaycuru/gde#67]
Em certos níveis de zoom da página (minha tela é pequena e eu uso 170%), fica basicamente impossível clicar na lupa e no pequeno menu com as opções de pesquisa por conta da faixinha "fork me on github"

![Captura de tela de 2021-07-13 14-50-07](https://user-images.githubusercontent.com/4229115/125501406-8d51e218-3ccb-4769-b503-2601901a02b2.png)

**Comment by guaycuru** [comment]
Resolvido!
