### ISSUE TITLE
nao consigo fazer a alteração de curso

### ISSUE THREAD

**Issue by daniellima551** [guaycuru/gde#68]
mudei do curso 89 ( eng ambiental) para o curso 39 (eng química) porem quando faço mudança no ide sempre da erro, 
<img width="1440" alt="Captura de Tela 2021-08-12 às 08 46 44" src="https://user-images.githubusercontent.com/88833658/129192126-4e20812c-3d52-4282-8277-54ff962bd156.png">
alguém sabe como me ajudar?

**Comment by guaycuru** [comment]
Tente usar outro navegador, Infelizmente o Safari por algum motivo que ainda não consegui descobrir não funciona nessa página.
Ver #57
