### ISSUE TITLE
Quebra de pré-requisitos

### ISSUE THREAD

**Issue by bbeazi** [guaycuru/gde#70]
Desde que eu mudei de curso não consigo mais utilizar o GDE, porque ele não dá a opção de você montar seu planejador se você não cursou a disciplina que é pré-requisito para uma atual que você está fazendo no momento. Penso que seria muito interessante, se fosse mais flexível essa questão, dado que a gente faz uma quebra de requisito e só passa a cursar as que estão faltando no semestre seguinte (falando de disiciplinas que só são disponibilizadas em semestres ímpares) principalmente para a galera que é do remanejamento interno e acaba tendo uma integralização e planejamento diferente.

**Comment by guaycuru** [comment]
Hmm não sabia que existia essa opção. De qualquer forma isso não deveria impedir você de utilizar o planejador.
Ele dá algum erro? O que exatamente acontece?

**Comment by bbeazi** [comment]
Bom, quando eu tento adicionar a disciplina no planejador aparece a mensagem _Você não podera cursar essa disciplina em 2022 - 2º semestre, pois não cursou um ou mais de seus pré-requisitos_, mas acontece que eu já estou cursando a disciplina e esse pré-requisito que pede eu só vou cursar no próximo semestre

**Comment by guaycuru** [comment]
E tem certeza que você pode cursar essa disciplina no segundo semestre?
Infelizmente a única forma que consigo pensar de resolver isso é marcar o pré-requisito como cursado...

**Comment by bbeazi** [comment]
Ah, posso sim, como é remanejamento ocorre quebra caso a pessoa não tenha cursado o pré-requisito! Mas então acho que farei isso mesmo e no próximo semestre adicionar de volta
