### ISSUE TITLE
Problemas com pré-requisitos da disciplina EL774

### ISSUE THREAD

**Issue by zFazan** [guaycuru/gde#72]
Olá! Tudo bem?

Curso Geografia (catálogo 2020), RA: 171580, e no próximo semestre irei cursar a disciplina EL774 (Estágio Supervisionado I). Já cursei todos os pré-requisitos que constam no catálogo (EL212; EL511; EL683). Aparecem mais duas disciplinas de pré-requisitos: EF632 e EF683, que acredito serem para alunos da FEF.

**Comment by guaycuru** [comment]
Olá!

De acordo com a DAC, para o seu catálogo (2020), os pré-requisitos para EL774 são: 
AA200 e AA445 OU
AA445 e EF632 e EF832 e EL683 OU
**AA445 e EL212 e EL511 e EL683**

Veja: https://www.dac.unicamp.br/sistemas/catalogos/grad/catalogo2020/coordenadorias/0005/0005.html#EL774

Isso é exatamente o que consta no GDE: https://grade.daconline.unicamp.br/disciplina/1985/

![image](https://user-images.githubusercontent.com/1985884/205612083-27c21c6f-0057-4c2c-8902-3e31e6362cd3.png)

Ou seja, para poder cursar EL774 você ainda precisa cursar AA445, o que significa ter CP de pelo menos 0,45 (ter concluído pelo menos 45% do currículo do seu curso).
