### ISSUE TITLE
Disciplina não some da árvore

### ISSUE THREAD

**Issue by ulasag** [guaycuru/gde#74]
Tentei diversas vezes eliminar a disciplina EQ050 da minha árvore, ela já aparece marcada como "cursei e obtive mais do que 5", mas não desaparece árvore.

**Comment by guaycuru** [comment]
Olá, poderia por favor me passar seu RA para que eu possa verificar?

**Comment by ulasag** [comment]
Boa tarde!
A disciplina saiu da minha árvore, acredito que eu não estava visualizando
o semestre atual, e sim um passado.

At.te,

Gabriela Ulasa
RA: 172815
Faculdade de Engenharia Química
UNICAMP

Em ter, 4 de jul de 2023 09:41, Felipe Guaycuru ***@***.***>
escreveu:

**Comment by guaycuru** [comment]
Acredito ter corrigido o problema.
Muito obrigado por avisar!
