### ISSUE TITLE
Exibição do curso

### ISSUE THREAD

**Issue by cesarenero** [guaycuru/gde#76]
Não aparece o nome do meu curso ao buscar meu nome ou na lista de alunos de uma turma

**Comment by guaycuru** [comment]
Olá. Não sei se entendi, como assim não aparece o nome do seu curso ao buscar seu nome?
Além disso, qual seu RA?

**Comment by cesarenero** [comment]
Por exemplo: quando busco uma turma a qual estou matriculado, nas minhas informações não aparece o curso, somente o nome
ra: 220277
