### ISSUE TITLE
Crédito de uma disciplina difere do valor mostrado na DAC.

### ISSUE THREAD

**Issue by ImP-Gamer** [guaycuru/gde#77]
De acordo com a DAC, Introdução a análise (MA507) vale 8 créditos, mas de acordo com o GDE são 6 créditos.

No GDE:
![image](https://github.com/guaycuru/gde/assets/23055104/f6fce075-2315-4065-ac26-e6bfcbcf8cf7)

Na DAC:
![image](https://github.com/guaycuru/gde/assets/23055104/a0547417-87ad-40b6-aaac-87390f59ae91)

Também seria útil adicionar a funcionalidade dos alunos adicionarem prereqs como AA440, já que, pelo cálculo incorreto do GDE, não consigo utilizar o planejador para o próximo semestre.

**Comment by guaycuru** [comment]
Infelizmente isso é sabido e não há como corrigir no momento.
Acontece que o número de disciplinas na DAC varia com o catálogo, mas no GDE o número de créditos da disciplina é fixo.
