### ISSUE TITLE
Período planejado

### ISSUE THREAD

**Issue by HoudiniGM** [guaycuru/gde#82]
Por conta do "período atual" permanecer como "
2023 - 2º Semestre", o "Período planejado" continua sendo "2024 - 1º Semestre".

Por conta disso, eu não consigo usar o planejador para montar horários das disciplinas para 2024/2.
![image](https://github.com/guaycuru/gde/assets/104776668/c3ab0e8f-7071-40c2-93b1-5bd0d1277df7)

**Comment by guaycuru** [comment]
Obrigado por avisar, o problema foi corrigido.

**Comment by HoudiniGM** [comment]
Que rápido kkkk Obrigado!
