### ISSUE TITLE
Não consigo logar no GDE

### ISSUE THREAD

**Issue by v1cav1ca** [guaycuru/gde#83]
Não estou conseguindo entrar no GDE. Vc pode me ajudar, por favor? 
Coloco meu email e senha, peço para entrar, fala que está errado. Peço para entrar pela DAC, não consigo. Cai nessa página:
![Captura de tela 2024-07-02 180046](https://github.com/guaycuru/gde/assets/101053257/8fe5e3aa-85dd-48b1-986c-9fd7b15b1b0d)
Abro outra aba com o GDE, pede novamente pra fazer login, tento fazer pela DAC, não consigo. Esse problema está persistindo há dias.

**Comment by guaycuru** [comment]
A senha do GDE é diferente da senha da DAC. Quando você pede para fazer login pela DAC, você está usando seu RA e senha dos sistemas acadêmicos (SIGA, etc)?
Qual o seu RA?

**Comment by v1cav1ca** [comment]
Sim, eu estava usando a senha do sistema SIGA, pq tava tentando logar pela DAC. Mas não conseguia entrar no GDE mesmo fazendo o login pela dac - isso no computador. Fiz a mesma coisa no celular (entrei no site do GDE, pedi pra fazer login via DAC, coloquei usuário e senha na DAC) e ai saiu desse loop, e consegui logar.

**Comment by guaycuru** [comment]
Ah que bom! Qualquer dúvida nos avise!
